stages:
  - prepare
  - backup
  - deploy

variables:
  SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
  SERVER_USER: $SERVER_USER
  SERVER_IP: $SERVER_IP
  BACKUP_DIR: $BACKUP_DIR
  DEPLOY_DIR: $DEPLOY_DIR

before_script:
  - apk update && apk add --no-cache openssh-client tar rsync
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -p 65002 $SERVER_IP >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - echo -e "Host *\n  StrictHostKeyChecking no\n  Port 65002" >> ~/.ssh/config

prepare:
  image: alpine:latest
  stage: prepare
  script:
    - echo "Preparation OK"
  only:
    - master

backup:
  image: alpine:latest
  stage: backup
  script:
    - DATE=$(date +%d-%m-%Y-%Hh-%Mm-%Ss)
    - echo "Creating local backup directory at $BACKUP_DIR/backup_$DATE"
    - mkdir -p $BACKUP_DIR/backup_$DATE
    - echo "Creating backup archive"
    - tar czf $BACKUP_DIR/backup_$DATE/backup.tar.gz --exclude=$BACKUP_DIR/backup_$DATE/backup.tar.gz .
    - echo "Ensuring remote directory exists"
    - ssh $SERVER_USER@$SERVER_IP "mkdir -p $BACKUP_DIR/backup_$DATE && echo 'Deny from all' > $BACKUP_DIR/.htaccess"
    - echo "Transferring backup file"
    - scp -P 65002 $BACKUP_DIR/backup_$DATE/backup.tar.gz $SERVER_USER@$SERVER_IP:$BACKUP_DIR/backup_$DATE/
  only:
    - master

deploy:
  image: alpine:latest
  stage: deploy
  script:
    - echo "DEPLOY_DIR=$DEPLOY_DIR"
    - ssh $SERVER_USER@$SERVER_IP "echo 'pwd:' && pwd && echo 'deploy dir:' && ls $DEPLOY_DIR 2>&1 | head -5 || echo 'DOSSIER INTROUVABLE'"
    - rsync -avz -e "ssh -p 65002" --exclude='.git*' --exclude='config.php' --exclude='reviews_cache.json' --exclude='planet-iris-backup/' --delete . $SERVER_USER@$SERVER_IP:$DEPLOY_DIR/
  only:
    - master
